### ISSUE TITLE
Packages/Installed Packages

### ISSUE THREAD

**Issue by stdavis** [guillermooo/AAAPT#3]
The `README` mentions copying `AAAPT.sublime-package` to _Packages/Installed Packages_. I don't see _Installed Packages_ in my _Packages_ folder. Am I missing something, or are you talking about the _Installed Packages_ folder that's a **sibling** of _Packages_?

![image](https://f.cloud.github.com/assets/1326248/1408035/56e6d74e-3d7a-11e3-8ca5-897c4d3f55d9.png)

**Comment by guillermooo** [comment]
You're right, it's a mistake. Thanks!
